---
- name: build ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  user: root

  vars_files:
    - "group_vars/all/vars"
    - "group_vars/all/vault"
  roles:
    - { role: manage-ec2-instances }
